-- Carzon — canonical passenger-vehicle model-line catalog.
--
-- UI vocabulary only. listings.make / listings.model remain TEXT.
-- No FK, no listing backfill, no discovery/official-data contract change.
-- Seed is editorial model lines (current + historically traded), not trims.

create table if not exists public.vehicle_model_catalog (
    id uuid primary key default gen_random_uuid(),
    make text not null,
    model text not null,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    constraint vehicle_model_catalog_make_chk
        check (btrim(make) <> ''),
    constraint vehicle_model_catalog_model_chk
        check (btrim(model) <> '')
);

create unique index if not exists vehicle_model_catalog_make_model_uniq
    on public.vehicle_model_catalog (lower(btrim(make)), lower(btrim(model)));

create index if not exists vehicle_model_catalog_active_make_idx
    on public.vehicle_model_catalog (lower(btrim(make)), model)
    where is_active;

comment on table public.vehicle_model_catalog is
    'Public reference catalog of canonical passenger model lines per make. '
    'Does not replace listings.model text persistence.';

alter table public.vehicle_model_catalog enable row level security;

revoke all on table public.vehicle_model_catalog from public;
revoke all on table public.vehicle_model_catalog from anon;
revoke all on table public.vehicle_model_catalog from authenticated;

create or replace function public.list_vehicle_models_for_make(p_make text)
returns table (model text)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
    select c.model
      from public.vehicle_model_catalog c
     where c.is_active
       and btrim(coalesce(p_make, '')) <> ''
       and lower(btrim(c.make)) = lower(btrim(p_make))
     order by c.model;
$$;

comment on function public.list_vehicle_models_for_make(text) is
    'Public read of active canonical model-line names for a make. '
    'Case-insensitive make match; alphabetical; no listing mutation.';

revoke all on function public.list_vehicle_models_for_make(text) from public;
grant execute on function public.list_vehicle_models_for_make(text)
    to anon, authenticated;

insert into public.vehicle_model_catalog (make, model)
values
    ('Toyota', 'Corolla'),
    ('Toyota', 'Camry'),
    ('Toyota', 'RAV4'),
    ('Toyota', 'Highlander'),
    ('Toyota', 'Yaris'),
    ('Toyota', 'Auris'),
    ('Toyota', 'Avensis'),
    ('Toyota', 'Prius'),
    ('Toyota', 'C-HR'),
    ('Toyota', 'Corolla Cross'),
    ('Toyota', 'Land Cruiser'),
    ('Toyota', 'Land Cruiser Prado'),
    ('Toyota', 'Hilux'),
    ('Toyota', 'Tacoma'),
    ('Toyota', 'Tundra'),
    ('Toyota', '4Runner'),
    ('Toyota', 'Sequoia'),
    ('Toyota', 'Sienna'),
    ('Toyota', 'Previa'),
    ('Toyota', 'Estima'),
    ('Toyota', 'Alphard'),
    ('Toyota', 'Vellfire'),
    ('Toyota', 'Wish'),
    ('Toyota', 'Verso'),
    ('Toyota', 'Picnic'),
    ('Toyota', 'Ipsum'),
    ('Toyota', 'Celica'),
    ('Toyota', 'Supra'),
    ('Toyota', 'MR2'),
    ('Toyota', 'GT86'),
    ('Toyota', 'GR86'),
    ('Toyota', 'GR Yaris'),
    ('Toyota', 'GR Corolla'),
    ('Toyota', 'Aygo'),
    ('Toyota', 'Aygo X'),
    ('Toyota', 'IQ'),
    ('Toyota', 'Urban Cruiser'),
    ('Toyota', 'Urban Cruiser Taisor'),
    ('Toyota', 'bZ4X'),
    ('Toyota', 'Crown'),
    ('Toyota', 'Avalon'),
    ('Toyota', 'Venza'),
    ('Toyota', 'Harrier'),
    ('Toyota', 'Fortuner'),
    ('Toyota', 'FJ Cruiser'),
    ('Toyota', 'Tercel'),
    ('Toyota', 'Starlet'),
    ('Toyota', 'Carina'),
    ('Toyota', 'Carina E'),
    ('Toyota', 'Corona'),
    ('Toyota', 'Mark II'),
    ('Toyota', 'Chaser'),
    ('Toyota', 'Cresta'),
    ('Toyota', 'Soarer'),
    ('Toyota', 'Celica GT-Four'),
    ('Toyota', 'Matrix'),
    ('Toyota', 'Vitz'),
    ('Toyota', 'Passo'),
    ('Toyota', 'Rush'),
    ('Toyota', 'Raize'),
    ('Toyota', 'Innova'),
    ('Toyota', 'Hiace'),
    ('Toyota', 'Proace'),
    ('Toyota', 'Proace City'),
    ('Toyota', 'LiteAce'),
    ('Toyota', 'TownAce'),
    ('Toyota', 'Succeed'),
    ('Toyota', 'Probox'),
    ('Toyota', 'Sera'),
    ('Toyota', 'Cressida'),
    ('Toyota', 'Paseo'),
    ('Toyota', 'Echo'),
    ('Toyota', 'Solara'),
    ('Toyota', 'Mirai'),
    ('Volkswagen', 'Golf'),
    ('Volkswagen', 'Passat'),
    ('Volkswagen', 'Polo'),
    ('Volkswagen', 'Tiguan'),
    ('Volkswagen', 'Touareg'),
    ('Volkswagen', 'T-Roc'),
    ('Volkswagen', 'T-Cross'),
    ('Volkswagen', 'Touran'),
    ('Volkswagen', 'Caddy'),
    ('Volkswagen', 'Jetta'),
    ('Volkswagen', 'Arteon'),
    ('Volkswagen', 'Passat CC'),
    ('Volkswagen', 'CC'),
    ('Volkswagen', 'Scirocco'),
    ('Volkswagen', 'Beetle'),
    ('Volkswagen', 'New Beetle'),
    ('Volkswagen', 'Sharan'),
    ('Volkswagen', 'Multivan'),
    ('Volkswagen', 'Caravelle'),
    ('Volkswagen', 'Transporter'),
    ('Volkswagen', 'California'),
    ('Volkswagen', 'ID.3'),
    ('Volkswagen', 'ID.4'),
    ('Volkswagen', 'ID.5'),
    ('Volkswagen', 'ID.7'),
    ('Volkswagen', 'ID. Buzz'),
    ('Volkswagen', 'e-Golf'),
    ('Volkswagen', 'up!'),
    ('Volkswagen', 'Fox'),
    ('Volkswagen', 'Lupo'),
    ('Volkswagen', 'Bora'),
    ('Volkswagen', 'Vento'),
    ('Volkswagen', 'Santana'),
    ('Volkswagen', 'Phaeton'),
    ('Volkswagen', 'Amarok'),
    ('Volkswagen', 'Crafter'),
    ('Volkswagen', 'LT'),
    ('Volkswagen', 'Corrado'),
    ('Volkswagen', 'Eos'),
    ('Volkswagen', 'Golf Plus'),
    ('Volkswagen', 'Golf Sportsvan'),
    ('Volkswagen', 'Taigo'),
    ('Volkswagen', 'Taos'),
    ('Volkswagen', 'Atlas'),
    ('Volkswagen', 'Routan'),
    ('Volkswagen', 'Pointer'),
    ('Volkswagen', 'Gol'),
    ('Volkswagen', 'Saveiro'),
    ('Volkswagen', 'Tiguan Allspace'),
    ('Skoda', 'Fabia'),
    ('Skoda', 'Octavia'),
    ('Skoda', 'Superb'),
    ('Skoda', 'Karoq'),
    ('Skoda', 'Kodiaq'),
    ('Skoda', 'Kamiq'),
    ('Skoda', 'Rapid'),
    ('Skoda', 'Scala'),
    ('Skoda', 'Roomster'),
    ('Skoda', 'Yeti'),
    ('Skoda', 'Citigo'),
    ('Skoda', 'Felicia'),
    ('Skoda', 'Favorit'),
    ('Skoda', 'Forman'),
    ('Skoda', '120'),
    ('Skoda', '135'),
    ('Skoda', 'Enyaq'),
    ('Skoda', 'Elroq'),
    ('Skoda', 'Kushaq'),
    ('Skoda', 'Slavia'),
    ('Skoda', 'Octavia Tour'),
    ('Opel', 'Astra'),
    ('Opel', 'Corsa'),
    ('Opel', 'Insignia'),
    ('Opel', 'Mokka'),
    ('Opel', 'Zafira'),
    ('Opel', 'Vectra'),
    ('Opel', 'Omega'),
    ('Opel', 'Meriva'),
    ('Opel', 'Combo'),
    ('Opel', 'Crossland'),
    ('Opel', 'Grandland'),
    ('Opel', 'Antara'),
    ('Opel', 'Frontera'),
    ('Opel', 'Kadett'),
    ('Opel', 'Ascona'),
    ('Opel', 'Calibra'),
    ('Opel', 'Tigra'),
    ('Opel', 'Adam'),
    ('Opel', 'Karl'),
    ('Opel', 'Agila'),
    ('Opel', 'Signum'),
    ('Opel', 'Cascada'),
    ('Opel', 'Ampera'),
    ('Opel', 'Ampera-e'),
    ('Opel', 'Rekord'),
    ('Opel', 'Senator'),
    ('Opel', 'Monterey'),
    ('Opel', 'Campo'),
    ('Opel', 'Movano'),
    ('Opel', 'Vivaro'),
    ('Opel', 'Combo Life'),
    ('Opel', 'Mokka X'),
    ('Opel', 'Zafira Tourer'),
    ('Opel', 'Astra GTC'),
    ('BMW', '1 Series'),
    ('BMW', '2 Series'),
    ('BMW', '3 Series'),
    ('BMW', '4 Series'),
    ('BMW', '5 Series'),
    ('BMW', '6 Series'),
    ('BMW', '7 Series'),
    ('BMW', '8 Series'),
    ('BMW', 'X1'),
    ('BMW', 'X2'),
    ('BMW', 'X3'),
    ('BMW', 'X4'),
    ('BMW', 'X5'),
    ('BMW', 'X6'),
    ('BMW', 'X7'),
    ('BMW', 'XM'),
    ('BMW', 'Z3'),
    ('BMW', 'Z4'),
    ('BMW', 'Z8'),
    ('BMW', 'i3'),
    ('BMW', 'i4'),
    ('BMW', 'i5'),
    ('BMW', 'i7'),
    ('BMW', 'i8'),
    ('BMW', 'iX'),
    ('BMW', 'iX1'),
    ('BMW', 'iX2'),
    ('BMW', 'iX3'),
    ('BMW', 'M2'),
    ('BMW', 'M3'),
    ('BMW', 'M4'),
    ('BMW', 'M5'),
    ('BMW', 'M6'),
    ('BMW', 'M8'),
    ('BMW', 'iX5'),
    ('Mercedes-Benz', 'A-Class'),
    ('Mercedes-Benz', 'B-Class'),
    ('Mercedes-Benz', 'C-Class'),
    ('Mercedes-Benz', 'E-Class'),
    ('Mercedes-Benz', 'S-Class'),
    ('Mercedes-Benz', 'CLA'),
    ('Mercedes-Benz', 'CLE'),
    ('Mercedes-Benz', 'CLK'),
    ('Mercedes-Benz', 'CLS'),
    ('Mercedes-Benz', 'GLA'),
    ('Mercedes-Benz', 'GLB'),
    ('Mercedes-Benz', 'GLC'),
    ('Mercedes-Benz', 'GLE'),
    ('Mercedes-Benz', 'GLS'),
    ('Mercedes-Benz', 'GLK'),
    ('Mercedes-Benz', 'GL-Class'),
    ('Mercedes-Benz', 'G-Class'),
    ('Mercedes-Benz', 'M-Class'),
    ('Mercedes-Benz', 'ML-Class'),
    ('Mercedes-Benz', 'R-Class'),
    ('Mercedes-Benz', 'SL'),
    ('Mercedes-Benz', 'SLK'),
    ('Mercedes-Benz', 'SLC'),
    ('Mercedes-Benz', 'SLS'),
    ('Mercedes-Benz', 'AMG GT'),
    ('Mercedes-Benz', 'EQA'),
    ('Mercedes-Benz', 'EQB'),
    ('Mercedes-Benz', 'EQC'),
    ('Mercedes-Benz', 'EQE'),
    ('Mercedes-Benz', 'EQS'),
    ('Mercedes-Benz', 'EQT'),
    ('Mercedes-Benz', 'EQV'),
    ('Mercedes-Benz', 'V-Class'),
    ('Mercedes-Benz', 'Vito'),
    ('Mercedes-Benz', 'Viano'),
    ('Mercedes-Benz', 'CL-Class'),
    ('Mercedes-Benz', 'CLC'),
    ('Mercedes-Benz', '190'),
    ('Mercedes-Benz', 'W124'),
    ('Mercedes-Benz', 'W201'),
    ('Mercedes-Benz', 'X-Class'),
    ('Mercedes-Benz', 'Citan'),
    ('Mercedes-Benz', 'T-Class'),
    ('Audi', 'A1'),
    ('Audi', 'A2'),
    ('Audi', 'A3'),
    ('Audi', 'A4'),
    ('Audi', 'A5'),
    ('Audi', 'A6'),
    ('Audi', 'A7'),
    ('Audi', 'A8'),
    ('Audi', 'Q2'),
    ('Audi', 'Q3'),
    ('Audi', 'Q4 e-tron'),
    ('Audi', 'Q5'),
    ('Audi', 'Q6 e-tron'),
    ('Audi', 'Q7'),
    ('Audi', 'Q8'),
    ('Audi', 'TT'),
    ('Audi', 'R8'),
    ('Audi', 'e-tron'),
    ('Audi', 'e-tron GT'),
    ('Audi', '80'),
    ('Audi', '90'),
    ('Audi', '100'),
    ('Audi', '200'),
    ('Audi', 'V8'),
    ('Audi', 'Cabriolet'),
    ('Audi', 'Coupe'),
    ('Audi', 'RS4'),
    ('Audi', 'RS5'),
    ('Audi', 'RS6'),
    ('Audi', 'RS7'),
    ('Audi', 'RS Q3'),
    ('Audi', 'RS Q8'),
    ('Audi', 'S3'),
    ('Audi', 'S4'),
    ('Audi', 'S5'),
    ('Audi', 'S6'),
    ('Audi', 'S7'),
    ('Audi', 'S8'),
    ('Audi', 'SQ5'),
    ('Audi', 'SQ7'),
    ('Audi', 'SQ8'),
    ('Audi', 'allroad'),
    ('Audi', 'A4 allroad'),
    ('Audi', 'A6 allroad'),
    ('Volvo', 'S40'),
    ('Volvo', 'S60'),
    ('Volvo', 'S70'),
    ('Volvo', 'S80'),
    ('Volvo', 'S90'),
    ('Volvo', 'V40'),
    ('Volvo', 'V50'),
    ('Volvo', 'V60'),
    ('Volvo', 'V70'),
    ('Volvo', 'V90'),
    ('Volvo', 'XC40'),
    ('Volvo', 'XC60'),
    ('Volvo', 'XC70'),
    ('Volvo', 'XC90'),
    ('Volvo', 'C30'),
    ('Volvo', 'C70'),
    ('Volvo', 'C40'),
    ('Volvo', 'EX30'),
    ('Volvo', 'EX90'),
    ('Volvo', '240'),
    ('Volvo', '740'),
    ('Volvo', '760'),
    ('Volvo', '850'),
    ('Volvo', '940'),
    ('Volvo', '960'),
    ('Volvo', '440'),
    ('Volvo', '460'),
    ('Volvo', '480'),
    ('Volvo', 'EC40'),
    ('Volvo', 'EX40'),
    ('Ford', 'Focus'),
    ('Ford', 'Fiesta'),
    ('Ford', 'Mondeo'),
    ('Ford', 'Fusion'),
    ('Ford', 'Mustang'),
    ('Ford', 'Kuga'),
    ('Ford', 'Escape'),
    ('Ford', 'Explorer'),
    ('Ford', 'Edge'),
    ('Ford', 'Puma'),
    ('Ford', 'EcoSport'),
    ('Ford', 'Ranger'),
    ('Ford', 'F-150'),
    ('Ford', 'Maverick'),
    ('Ford', 'Bronco'),
    ('Ford', 'Bronco Sport'),
    ('Ford', 'Transit'),
    ('Ford', 'Tourneo'),
    ('Ford', 'Tourneo Connect'),
    ('Ford', 'Tourneo Custom'),
    ('Ford', 'S-Max'),
    ('Ford', 'Galaxy'),
    ('Ford', 'C-Max'),
    ('Ford', 'B-Max'),
    ('Ford', 'Ka'),
    ('Ford', 'Ka+'),
    ('Ford', 'Escort'),
    ('Ford', 'Sierra'),
    ('Ford', 'Scorpio'),
    ('Ford', 'Granada'),
    ('Ford', 'Orion'),
    ('Ford', 'Capri'),
    ('Ford', 'Cougar'),
    ('Ford', 'Probe'),
    ('Ford', 'Taurus'),
    ('Ford', 'Fusion US'),
    ('Ford', 'Explorer Sport Trac'),
    ('Ford', 'Expedition'),
    ('Ford', 'Everest'),
    ('Ford', 'Territory'),
    ('Ford', 'Ranger Raptor'),
    ('Ford', 'Mustang Mach-E'),
    ('Ford', 'Tourneo Courier'),
    ('Ford', 'Connect'),
    ('Ford', 'Transit Custom'),
    ('Ford', 'Transit Connect'),
    ('Ford', 'StreetKa'),
    ('Fiat', '500'),
    ('Fiat', '500X'),
    ('Fiat', '500L'),
    ('Fiat', '500e'),
    ('Fiat', 'Panda'),
    ('Fiat', 'Punto'),
    ('Fiat', 'Grande Punto'),
    ('Fiat', 'Tipo'),
    ('Fiat', 'Bravo'),
    ('Fiat', 'Brava'),
    ('Fiat', 'Stilo'),
    ('Fiat', 'Croma'),
    ('Fiat', 'Linea'),
    ('Fiat', 'Albea'),
    ('Fiat', 'Doblo'),
    ('Fiat', 'Qubo'),
    ('Fiat', 'Fiorino'),
    ('Fiat', 'Ducato'),
    ('Fiat', 'Scudo'),
    ('Fiat', 'Talento'),
    ('Fiat', 'Ulysse'),
    ('Fiat', 'Multipla'),
    ('Fiat', 'Cinquecento'),
    ('Fiat', 'Seicento'),
    ('Fiat', 'Uno'),
    ('Fiat', 'Palio'),
    ('Fiat', 'Siena'),
    ('Fiat', 'Marea'),
    ('Fiat', 'Barchetta'),
    ('Fiat', 'Coupe'),
    ('Fiat', '124 Spider'),
    ('Fiat', 'X1/9'),
    ('Fiat', 'Panda Cross'),
    ('Fiat', '600'),
    ('Fiat', 'Topolino'),
    ('Fiat', 'Fullback'),
    ('Fiat', 'Freemont'),
    ('Fiat', 'Sedici'),
    ('Honda', 'Accord'),
    ('Honda', 'Civic'),
    ('Honda', 'CR-V'),
    ('Honda', 'HR-V'),
    ('Honda', 'Jazz'),
    ('Honda', 'Fit'),
    ('Honda', 'City'),
    ('Honda', 'Insight'),
    ('Honda', 'CR-Z'),
    ('Honda', 'FR-V'),
    ('Honda', 'Stream'),
    ('Honda', 'Odyssey'),
    ('Honda', 'Pilot'),
    ('Honda', 'Passport'),
    ('Honda', 'Ridgeline'),
    ('Honda', 'Prelude'),
    ('Honda', 'S2000'),
    ('Honda', 'Integra'),
    ('Honda', 'Legend'),
    ('Honda', 'Element'),
    ('Honda', 'Crosstour'),
    ('Honda', 'ZR-V'),
    ('Honda', 'e:Ny1'),
    ('Honda', 'CRX'),
    ('Honda', 'NSX'),
    ('Honda', 'Shuttle'),
    ('Honda', 'Concerto'),
    ('Honda', 'Logo'),
    ('Honda', 'Ballade'),
    ('Honda', 'Quintet'),
    ('Honda', 'Stepwgn'),
    ('Honda', 'Freed'),
    ('Honda', 'Mobilio'),
    ('Honda', 'S660'),
    ('Honda', 'Beat'),
    ('Honda', 'Today'),
    ('Honda', 'Life'),
    ('Honda', 'Acty'),
    ('Honda', 'Crossroad'),
    ('Hyundai', 'Accent'),
    ('Hyundai', 'Elantra'),
    ('Hyundai', 'i10'),
    ('Hyundai', 'i20'),
    ('Hyundai', 'i30'),
    ('Hyundai', 'i40'),
    ('Hyundai', 'iX20'),
    ('Hyundai', 'iX35'),
    ('Hyundai', 'Tucson'),
    ('Hyundai', 'Santa Fe'),
    ('Hyundai', 'Kona'),
    ('Hyundai', 'Bayon'),
    ('Hyundai', 'Ioniq'),
    ('Hyundai', 'Ioniq 5'),
    ('Hyundai', 'Ioniq 6'),
    ('Hyundai', 'Ioniq 9'),
    ('Hyundai', 'Sonata'),
    ('Hyundai', 'Grandeur'),
    ('Hyundai', 'Genesis Coupe'),
    ('Hyundai', 'Veloster'),
    ('Hyundai', 'Getz'),
    ('Hyundai', 'Atos'),
    ('Hyundai', 'Matrix'),
    ('Hyundai', 'Lavita'),
    ('Hyundai', 'Coupe'),
    ('Hyundai', 'Tiburon'),
    ('Hyundai', 'Trajet'),
    ('Hyundai', 'Terracan'),
    ('Hyundai', 'Galloper'),
    ('Hyundai', 'H-1'),
    ('Hyundai', 'Staria'),
    ('Hyundai', 'Palisade'),
    ('Hyundai', 'Venue'),
    ('Hyundai', 'Creta'),
    ('Hyundai', 'Alcazar'),
    ('Hyundai', 'Verna'),
    ('Hyundai', 'Solaris'),
    ('Hyundai', 'Porter'),
    ('Hyundai', 'Santa Cruz'),
    ('Hyundai', 'Nexo'),
    ('Hyundai', 'Stellar'),
    ('Hyundai', 'Pony'),
    ('Hyundai', 'Excel'),
    ('Hyundai', 'Lantra'),
    ('Hyundai', 'XG'),
    ('Kia', 'Ceed'),
    ('Kia', 'Rio'),
    ('Kia', 'Sportage'),
    ('Kia', 'Sorento'),
    ('Kia', 'Picanto'),
    ('Kia', 'Cerato'),
    ('Kia', 'Forte'),
    ('Kia', 'Optima'),
    ('Kia', 'K5'),
    ('Kia', 'K8'),
    ('Kia', 'Stonic'),
    ('Kia', 'Niro'),
    ('Kia', 'Soul'),
    ('Kia', 'Carnival'),
    ('Kia', 'Sedona'),
    ('Kia', 'Carens'),
    ('Kia', 'Venga'),
    ('Kia', 'Pride'),
    ('Kia', 'Sephia'),
    ('Kia', 'Shuma'),
    ('Kia', 'Clarus'),
    ('Kia', 'Magentis'),
    ('Kia', 'Opirus'),
    ('Kia', 'Cadenza'),
    ('Kia', 'Stinger'),
    ('Kia', 'EV3'),
    ('Kia', 'EV6'),
    ('Kia', 'EV9'),
    ('Kia', 'EV5'),
    ('Kia', 'Seltos'),
    ('Kia', 'Sonet'),
    ('Kia', 'Telluride'),
    ('Kia', 'Mohave'),
    ('Kia', 'Borrego'),
    ('Kia', 'Proceed'),
    ('Kia', 'XCeed'),
    ('Kia', 'K3'),
    ('Kia', 'K4'),
    ('Kia', 'K7'),
    ('Kia', 'K9'),
    ('Kia', 'K900'),
    ('Kia', 'Spectra'),
    ('Kia', 'Amanti'),
    ('Kia', 'Rondo'),
    ('Nissan', 'Micra'),
    ('Nissan', 'Qashqai'),
    ('Nissan', 'Juke'),
    ('Nissan', 'X-Trail'),
    ('Nissan', 'Note'),
    ('Nissan', 'Tiida'),
    ('Nissan', 'Almera'),
    ('Nissan', 'Sunny'),
    ('Nissan', 'Primera'),
    ('Nissan', 'Maxima'),
    ('Nissan', 'Altima'),
    ('Nissan', 'Sentra'),
    ('Nissan', 'Leaf'),
    ('Nissan', 'Ariya'),
    ('Nissan', 'Navara'),
    ('Nissan', 'Frontier'),
    ('Nissan', 'Pathfinder'),
    ('Nissan', 'Murano'),
    ('Nissan', 'Terrano'),
    ('Nissan', 'Patrol'),
    ('Nissan', 'Armada'),
    ('Nissan', '370Z'),
    ('Nissan', '350Z'),
    ('Nissan', '300ZX'),
    ('Nissan', 'GT-R'),
    ('Nissan', 'Skyline'),
    ('Nissan', 'Silvia'),
    ('Nissan', '200SX'),
    ('Nissan', '240SX'),
    ('Nissan', 'Cube'),
    ('Nissan', 'Qashqai+2'),
    ('Nissan', 'Pulsar'),
    ('Nissan', 'Almera Tino'),
    ('Nissan', 'Tino'),
    ('Nissan', 'Serena'),
    ('Nissan', 'Elgrand'),
    ('Nissan', 'Presage'),
    ('Nissan', 'Lafesta'),
    ('Nissan', 'Teana'),
    ('Nissan', 'Bluebird'),
    ('Nissan', 'Bluebird Sylphy'),
    ('Nissan', 'Wingroad'),
    ('Nissan', 'AD'),
    ('Nissan', 'NV200'),
    ('Nissan', 'Primastar'),
    ('Nissan', 'Interstar'),
    ('Nissan', 'NP300'),
    ('Nissan', 'Xterra'),
    ('Nissan', 'Rogue'),
    ('Nissan', 'Kicks'),
    ('Nissan', 'Versa'),
    ('Nissan', 'Quest'),
    ('Nissan', 'Titan'),
    ('Renault', 'Clio'),
    ('Renault', 'Megane'),
    ('Renault', 'Scenic'),
    ('Renault', 'Captur'),
    ('Renault', 'Kadjar'),
    ('Renault', 'Austral'),
    ('Renault', 'Twingo'),
    ('Renault', 'Modus'),
    ('Renault', 'Espace'),
    ('Renault', 'Laguna'),
    ('Renault', 'Talisman'),
    ('Renault', 'Fluence'),
    ('Renault', 'Latitude'),
    ('Renault', 'Safrane'),
    ('Renault', '19'),
    ('Renault', '21'),
    ('Renault', '25'),
    ('Renault', 'Symbol'),
    ('Renault', 'Logan'),
    ('Renault', 'Sandero'),
    ('Renault', 'Duster'),
    ('Renault', 'Koleos'),
    ('Renault', 'Arkana'),
    ('Renault', 'Rafale'),
    ('Renault', 'Symbioz'),
    ('Renault', '5'),
    ('Renault', '4'),
    ('Renault', 'Twizy'),
    ('Renault', 'Zoe'),
    ('Renault', 'Kangoo'),
    ('Renault', 'Trafic'),
    ('Renault', 'Master'),
    ('Renault', 'Grand Scenic'),
    ('Renault', 'Avantime'),
    ('Renault', 'Vel Satis'),
    ('Renault', 'Wind'),
    ('Renault', 'Express'),
    ('Renault', 'Triber'),
    ('Renault', 'Kiger'),
    ('Peugeot', '208'),
    ('Peugeot', '308'),
    ('Peugeot', '508'),
    ('Peugeot', '2008'),
    ('Peugeot', '3008'),
    ('Peugeot', '5008'),
    ('Peugeot', '107'),
    ('Peugeot', '206'),
    ('Peugeot', '207'),
    ('Peugeot', '307'),
    ('Peugeot', '407'),
    ('Peugeot', '607'),
    ('Peugeot', '1007'),
    ('Peugeot', '4007'),
    ('Peugeot', '4008'),
    ('Peugeot', '806'),
    ('Peugeot', '807'),
    ('Peugeot', 'Partner'),
    ('Peugeot', 'Rifter'),
    ('Peugeot', 'Expert'),
    ('Peugeot', 'Traveller'),
    ('Peugeot', 'Boxer'),
    ('Peugeot', 'iOn'),
    ('Peugeot', '108'),
    ('Peugeot', '301'),
    ('Peugeot', '408'),
    ('Peugeot', '406'),
    ('Peugeot', '405'),
    ('Peugeot', '306'),
    ('Peugeot', '205'),
    ('Peugeot', '106'),
    ('Peugeot', '309'),
    ('Peugeot', '605'),
    ('Peugeot', '504'),
    ('Peugeot', '505'),
    ('Peugeot', 'RCZ'),
    ('Peugeot', 'Bipper'),
    ('Peugeot', 'Partner Tepee'),
    ('Citroen', 'C3'),
    ('Citroen', 'C4'),
    ('Citroen', 'C5'),
    ('Citroen', 'Berlingo'),
    ('Citroen', 'C1'),
    ('Citroen', 'C2'),
    ('Citroen', 'C3 Aircross'),
    ('Citroen', 'C3 Picasso'),
    ('Citroen', 'C4 Picasso'),
    ('Citroen', 'C4 Cactus'),
    ('Citroen', 'C4 X'),
    ('Citroen', 'C5 Aircross'),
    ('Citroen', 'C5 X'),
    ('Citroen', 'C6'),
    ('Citroen', 'C8'),
    ('Citroen', 'Xsara'),
    ('Citroen', 'Xsara Picasso'),
    ('Citroen', 'Saxo'),
    ('Citroen', 'ZX'),
    ('Citroen', 'Xantia'),
    ('Citroen', 'XM'),
    ('Citroen', 'AX'),
    ('Citroen', 'BX'),
    ('Citroen', 'CX'),
    ('Citroen', 'GS'),
    ('Citroen', 'DS3'),
    ('Citroen', 'DS4'),
    ('Citroen', 'DS5'),
    ('Citroen', 'Nemo'),
    ('Citroen', 'Jumpy'),
    ('Citroen', 'SpaceTourer'),
    ('Citroen', 'Jumper'),
    ('Citroen', 'C-Elysee'),
    ('Citroen', 'C4 Aircross'),
    ('Citroen', 'C-Crosser'),
    ('Citroen', 'C15'),
    ('Citroen', 'Visa'),
    ('Citroen', 'Evasion'),
    ('Citroen', 'Synergie'),
    ('Citroen', 'Ami'),
    ('Dacia', 'Logan'),
    ('Dacia', 'Sandero'),
    ('Dacia', 'Duster'),
    ('Dacia', 'Lodgy'),
    ('Dacia', 'Dokker'),
    ('Dacia', 'Jogger'),
    ('Dacia', 'Spring'),
    ('Dacia', 'Bigster'),
    ('Dacia', 'Solenza'),
    ('Dacia', 'Nova'),
    ('Dacia', '1310'),
    ('Dacia', 'Pickup'),
    ('Dacia', 'Logan MCV'),
    ('Dacia', 'Sandero Stepway'),
    ('Dacia', 'Logan Stepway'),
    ('Mazda', 'Mazda2'),
    ('Mazda', 'Mazda3'),
    ('Mazda', 'Mazda5'),
    ('Mazda', 'Mazda6'),
    ('Mazda', 'CX-3'),
    ('Mazda', 'CX-30'),
    ('Mazda', 'CX-5'),
    ('Mazda', 'CX-50'),
    ('Mazda', 'CX-7'),
    ('Mazda', 'CX-9'),
    ('Mazda', 'CX-60'),
    ('Mazda', 'CX-70'),
    ('Mazda', 'CX-80'),
    ('Mazda', 'CX-90'),
    ('Mazda', 'MX-5'),
    ('Mazda', 'MX-30'),
    ('Mazda', 'MX-3'),
    ('Mazda', 'MX-6'),
    ('Mazda', 'RX-7'),
    ('Mazda', 'RX-8'),
    ('Mazda', 'Premacy'),
    ('Mazda', 'Tribute'),
    ('Mazda', 'BT-50'),
    ('Mazda', 'B-Series'),
    ('Mazda', '323'),
    ('Mazda', '626'),
    ('Mazda', '929'),
    ('Mazda', '121'),
    ('Mazda', 'Xedos 6'),
    ('Mazda', 'Xedos 9'),
    ('Mazda', 'MPV'),
    ('Mazda', 'Demio'),
    ('Mazda', 'Verisa'),
    ('Mazda', 'Axela'),
    ('Mazda', 'Atenza'),
    ('Mazda', 'CX-8'),
    ('Mazda', 'Roadster'),
    ('Mitsubishi', 'Lancer'),
    ('Mitsubishi', 'Lancer Evolution'),
    ('Mitsubishi', 'Outlander'),
    ('Mitsubishi', 'ASX'),
    ('Mitsubishi', 'Eclipse Cross'),
    ('Mitsubishi', 'Pajero'),
    ('Mitsubishi', 'Pajero Sport'),
    ('Mitsubishi', 'Montero'),
    ('Mitsubishi', 'Montero Sport'),
    ('Mitsubishi', 'L200'),
    ('Mitsubishi', 'Triton'),
    ('Mitsubishi', 'Galant'),
    ('Mitsubishi', 'Colt'),
    ('Mitsubishi', 'Carisma'),
    ('Mitsubishi', 'Space Star'),
    ('Mitsubishi', 'Space Wagon'),
    ('Mitsubishi', 'Space Runner'),
    ('Mitsubishi', 'Grandis'),
    ('Mitsubishi', 'RVR'),
    ('Mitsubishi', 'Eclipse'),
    ('Mitsubishi', '3000GT'),
    ('Mitsubishi', 'GTO'),
    ('Mitsubishi', 'Diamante'),
    ('Mitsubishi', 'Mirage'),
    ('Mitsubishi', 'Attrage'),
    ('Mitsubishi', 'i-MiEV'),
    ('Mitsubishi', 'Delica'),
    ('Mitsubishi', 'Delica D:5'),
    ('Mitsubishi', 'Challenger'),
    ('Mitsubishi', 'Endeavor'),
    ('Mitsubishi', 'Raider'),
    ('Mitsubishi', 'Sigma'),
    ('Mitsubishi', 'Starion'),
    ('Mitsubishi', 'Tredia'),
    ('Mitsubishi', 'Cordia'),
    ('Mitsubishi', 'Mighty Max'),
    ('Subaru', 'Impreza'),
    ('Subaru', 'Legacy'),
    ('Subaru', 'Outback'),
    ('Subaru', 'Forester'),
    ('Subaru', 'XV'),
    ('Subaru', 'Crosstrek'),
    ('Subaru', 'WRX'),
    ('Subaru', 'WRX STI'),
    ('Subaru', 'BRZ'),
    ('Subaru', 'Levorg'),
    ('Subaru', 'Tribeca'),
    ('Subaru', 'Justy'),
    ('Subaru', 'Vivio'),
    ('Subaru', 'SVX'),
    ('Subaru', 'Baja'),
    ('Subaru', 'Trezia'),
    ('Subaru', 'Exiga'),
    ('Subaru', 'Solterra'),
    ('Subaru', 'Ascent'),
    ('Suzuki', 'Swift'),
    ('Suzuki', 'Vitara'),
    ('Suzuki', 'Grand Vitara'),
    ('Suzuki', 'SX4'),
    ('Suzuki', 'SX4 S-Cross'),
    ('Suzuki', 'Jimny'),
    ('Suzuki', 'Ignis'),
    ('Suzuki', 'Baleno'),
    ('Suzuki', 'Celerio'),
    ('Suzuki', 'Alto'),
    ('Suzuki', 'Wagon R'),
    ('Suzuki', 'Splash'),
    ('Suzuki', 'Liana'),
    ('Suzuki', 'Liana Aerio'),
    ('Suzuki', 'Aerio'),
    ('Suzuki', 'Forenza'),
    ('Suzuki', 'Reno'),
    ('Suzuki', 'Kizashi'),
    ('Suzuki', 'XL7'),
    ('Suzuki', 'Samurai'),
    ('Suzuki', 'Sidekick'),
    ('Suzuki', 'X-90'),
    ('Suzuki', 'Ciaz'),
    ('Suzuki', 'Dzire'),
    ('Suzuki', 'Ertiga'),
    ('Suzuki', 'S-Cross'),
    ('Suzuki', 'Across'),
    ('Suzuki', 'Swace'),
    ('Suzuki', 'Carry'),
    ('Suzuki', 'Every'),
    ('Suzuki', 'APV'),
    ('Seat', 'Ibiza'),
    ('Seat', 'Leon'),
    ('Seat', 'Arona'),
    ('Seat', 'Ateca'),
    ('Seat', 'Tarraco'),
    ('Seat', 'Toledo'),
    ('Seat', 'Altea'),
    ('Seat', 'Alhambra'),
    ('Seat', 'Cordoba'),
    ('Seat', 'Exeo'),
    ('Seat', 'Mii'),
    ('Seat', 'Inca'),
    ('Seat', 'Malaga'),
    ('Seat', 'Marbella'),
    ('Seat', 'Arosa'),
    ('Cupra', 'Formentor'),
    ('Cupra', 'Leon'),
    ('Cupra', 'Ateca'),
    ('Cupra', 'Born'),
    ('Cupra', 'Tavascan'),
    ('Cupra', 'Terramar'),
    ('Cupra', 'Leon Sportstourer'),
    ('Chevrolet', 'Cruze'),
    ('Chevrolet', 'Aveo'),
    ('Chevrolet', 'Lacetti'),
    ('Chevrolet', 'Lanos'),
    ('Chevrolet', 'Niva'),
    ('Chevrolet', 'Captiva'),
    ('Chevrolet', 'Orlando'),
    ('Chevrolet', 'Spark'),
    ('Chevrolet', 'Malibu'),
    ('Chevrolet', 'Impala'),
    ('Chevrolet', 'Camaro'),
    ('Chevrolet', 'Corvette'),
    ('Chevrolet', 'Tahoe'),
    ('Chevrolet', 'Suburban'),
    ('Chevrolet', 'Equinox'),
    ('Chevrolet', 'Traverse'),
    ('Chevrolet', 'Trax'),
    ('Chevrolet', 'Blazer'),
    ('Chevrolet', 'Colorado'),
    ('Chevrolet', 'Silverado'),
    ('Chevrolet', 'Trailblazer'),
    ('Chevrolet', 'Epica'),
    ('Chevrolet', 'Evanda'),
    ('Chevrolet', 'Rezzo'),
    ('Chevrolet', 'Tacuma'),
    ('Chevrolet', 'Kalos'),
    ('Chevrolet', 'Matiz'),
    ('Chevrolet', 'Cobalt'),
    ('Chevrolet', 'Volt'),
    ('Chevrolet', 'Bolt'),
    ('Chevrolet', 'Bolt EUV'),
    ('Chevrolet', 'Onix'),
    ('Chevrolet', 'Tracker'),
    ('Chevrolet', 'Spin'),
    ('Chevrolet', 'Avalanche'),
    ('Chevrolet', 'Express'),
    ('Chevrolet', 'Astro'),
    ('Chevrolet', 'Venture'),
    ('Chevrolet', 'Uplander'),
    ('Chevrolet', 'HHR'),
    ('Chevrolet', 'SSR'),
    ('Chevrolet', 'Monte Carlo'),
    ('Chevrolet', 'Caprice'),
    ('Chevrolet', 'Cavalier'),
    ('Chevrolet', 'Beretta'),
    ('Chevrolet', 'Corsica'),
    ('Chevrolet', 'Lumina'),
    ('Chevrolet', 'Nova'),
    ('Tesla', 'Model 3'),
    ('Tesla', 'Model S'),
    ('Tesla', 'Model X'),
    ('Tesla', 'Model Y'),
    ('Tesla', 'Cybertruck'),
    ('Tesla', 'Roadster'),
    ('Lexus', 'CT'),
    ('Lexus', 'IS'),
    ('Lexus', 'ES'),
    ('Lexus', 'GS'),
    ('Lexus', 'LS'),
    ('Lexus', 'LC'),
    ('Lexus', 'RC'),
    ('Lexus', 'UX'),
    ('Lexus', 'NX'),
    ('Lexus', 'RX'),
    ('Lexus', 'GX'),
    ('Lexus', 'LX'),
    ('Lexus', 'RZ'),
    ('Lexus', 'TX'),
    ('Lexus', 'HS'),
    ('Lexus', 'SC'),
    ('Lexus', 'LFA'),
    ('Land Rover', 'Defender'),
    ('Land Rover', 'Discovery'),
    ('Land Rover', 'Discovery Sport'),
    ('Land Rover', 'Freelander'),
    ('Land Rover', 'Range Rover'),
    ('Land Rover', 'Range Rover Sport'),
    ('Land Rover', 'Range Rover Evoque'),
    ('Land Rover', 'Range Rover Velar'),
    ('Land Rover', 'LR2'),
    ('Land Rover', 'LR3'),
    ('Land Rover', 'LR4'),
    ('Land Rover', 'Series I'),
    ('Land Rover', 'Series II'),
    ('Land Rover', 'Series III'),
    ('Land Rover', 'Range Rover Classic'),
    ('Jeep', 'Wrangler'),
    ('Jeep', 'Grand Cherokee'),
    ('Jeep', 'Cherokee'),
    ('Jeep', 'Compass'),
    ('Jeep', 'Renegade'),
    ('Jeep', 'Patriot'),
    ('Jeep', 'Commander'),
    ('Jeep', 'Gladiator'),
    ('Jeep', 'Wagoneer'),
    ('Jeep', 'Grand Wagoneer'),
    ('Jeep', 'Avenger'),
    ('Jeep', 'Liberty'),
    ('Jeep', 'CJ'),
    ('Porsche', '911'),
    ('Porsche', '718 Boxster'),
    ('Porsche', '718 Cayman'),
    ('Porsche', 'Boxster'),
    ('Porsche', 'Cayman'),
    ('Porsche', 'Cayenne'),
    ('Porsche', 'Macan'),
    ('Porsche', 'Panamera'),
    ('Porsche', 'Taycan'),
    ('Porsche', '918'),
    ('Porsche', '944'),
    ('Porsche', '968'),
    ('Porsche', '928'),
    ('Porsche', '924'),
    ('Porsche', 'Carrera GT'),
    ('Mini', 'Cooper'),
    ('Mini', 'Clubman'),
    ('Mini', 'Countryman'),
    ('Mini', 'Paceman'),
    ('Mini', 'Coupe'),
    ('Mini', 'Roadster'),
    ('Mini', 'Cabrio'),
    ('Mini', 'Hatch'),
    ('Mini', 'Aceman'),
    ('Smart', 'Fortwo'),
    ('Smart', 'Forfour'),
    ('Smart', '#1'),
    ('Smart', '#3'),
    ('Smart', 'Roadster'),
    ('Smart', 'Crossblade'),
    ('Alfa Romeo', 'Giulia'),
    ('Alfa Romeo', 'Stelvio'),
    ('Alfa Romeo', 'Tonale'),
    ('Alfa Romeo', 'Giulietta'),
    ('Alfa Romeo', 'Mito'),
    ('Alfa Romeo', '159'),
    ('Alfa Romeo', '156'),
    ('Alfa Romeo', '147'),
    ('Alfa Romeo', '146'),
    ('Alfa Romeo', '145'),
    ('Alfa Romeo', '166'),
    ('Alfa Romeo', '164'),
    ('Alfa Romeo', '155'),
    ('Alfa Romeo', '33'),
    ('Alfa Romeo', '75'),
    ('Alfa Romeo', '90'),
    ('Alfa Romeo', 'GT'),
    ('Alfa Romeo', 'GTV'),
    ('Alfa Romeo', 'Spider'),
    ('Alfa Romeo', 'Brera'),
    ('Alfa Romeo', '4C'),
    ('Alfa Romeo', '8C'),
    ('Alfa Romeo', 'Junior'),
    ('Alfa Romeo', '33 Stradale'),
    ('Alfa Romeo', 'SZ'),
    ('Alfa Romeo', 'RZ'),
    ('Alfa Romeo', 'Montreal'),
    ('Jaguar', 'XE'),
    ('Jaguar', 'XF'),
    ('Jaguar', 'XJ'),
    ('Jaguar', 'XK'),
    ('Jaguar', 'F-Type'),
    ('Jaguar', 'F-Pace'),
    ('Jaguar', 'E-Pace'),
    ('Jaguar', 'I-Pace'),
    ('Jaguar', 'S-Type'),
    ('Jaguar', 'X-Type'),
    ('Jaguar', 'XJS'),
    ('Jaguar', 'XJ6'),
    ('Jaguar', 'XJ8'),
    ('Jaguar', 'XJ12'),
    ('Jaguar', 'XK8'),
    ('Jaguar', 'XKR'),
    ('Chrysler', '300'),
    ('Chrysler', '300C'),
    ('Chrysler', '200'),
    ('Chrysler', 'Sebring'),
    ('Chrysler', 'PT Cruiser'),
    ('Chrysler', 'Voyager'),
    ('Chrysler', 'Grand Voyager'),
    ('Chrysler', 'Town & Country'),
    ('Chrysler', 'Pacifica'),
    ('Chrysler', 'Crossfire'),
    ('Chrysler', 'Neon'),
    ('Chrysler', 'Stratus'),
    ('Chrysler', 'Cirrus'),
    ('Chrysler', 'Concorde'),
    ('Chrysler', 'LHS'),
    ('Chrysler', 'New Yorker'),
    ('Chrysler', 'Imperial'),
    ('Chrysler', 'Aspen'),
    ('Dodge', 'Challenger'),
    ('Dodge', 'Charger'),
    ('Dodge', 'Durango'),
    ('Dodge', 'Journey'),
    ('Dodge', 'Caliber'),
    ('Dodge', 'Avenger'),
    ('Dodge', 'Nitro'),
    ('Dodge', 'Dart'),
    ('Dodge', 'Neon'),
    ('Dodge', 'Stratus'),
    ('Dodge', 'Intrepid'),
    ('Dodge', 'Magnum'),
    ('Dodge', 'Viper'),
    ('Dodge', 'Ram'),
    ('Dodge', 'Dakota'),
    ('Dodge', 'Caravan'),
    ('Dodge', 'Grand Caravan'),
    ('Dodge', 'Hornet'),
    ('Ram', '1500'),
    ('Ram', '2500'),
    ('Ram', '3500'),
    ('Ram', 'ProMaster'),
    ('Ram', 'ProMaster City'),
    ('GMC', 'Sierra'),
    ('GMC', 'Canyon'),
    ('GMC', 'Yukon'),
    ('GMC', 'Acadia'),
    ('GMC', 'Terrain'),
    ('GMC', 'Envoy'),
    ('GMC', 'Jimmy'),
    ('GMC', 'Safari'),
    ('GMC', 'Savana'),
    ('GMC', 'Hummer EV'),
    ('Lincoln', 'MKZ'),
    ('Lincoln', 'MKX'),
    ('Lincoln', 'MKC'),
    ('Lincoln', 'MKS'),
    ('Lincoln', 'MKT'),
    ('Lincoln', 'Navigator'),
    ('Lincoln', 'Aviator'),
    ('Lincoln', 'Nautilus'),
    ('Lincoln', 'Corsair'),
    ('Lincoln', 'Continental'),
    ('Lincoln', 'Town Car'),
    ('Lincoln', 'LS'),
    ('Lincoln', 'Zephyr'),
    ('Buick', 'Encore'),
    ('Buick', 'Enclave'),
    ('Buick', 'Envision'),
    ('Buick', 'Regal'),
    ('Buick', 'LaCrosse'),
    ('Buick', 'Lucerne'),
    ('Buick', 'Verano'),
    ('Buick', 'Cascada'),
    ('Buick', 'Park Avenue'),
    ('Buick', 'LeSabre'),
    ('Buick', 'Century'),
    ('Buick', 'Roadmaster'),
    ('Buick', 'Electra'),
    ('Buick', 'Riviera'),
    ('Hummer', 'H1'),
    ('Hummer', 'H2'),
    ('Hummer', 'H3'),
    ('Hummer', 'H3T'),
    ('Hummer', 'EV'),
    ('Cadillac', 'CT4'),
    ('Cadillac', 'CT5'),
    ('Cadillac', 'CT6'),
    ('Cadillac', 'CTS'),
    ('Cadillac', 'ATS'),
    ('Cadillac', 'XTS'),
    ('Cadillac', 'STS'),
    ('Cadillac', 'DTS'),
    ('Cadillac', 'XT4'),
    ('Cadillac', 'XT5'),
    ('Cadillac', 'XT6'),
    ('Cadillac', 'SRX'),
    ('Cadillac', 'Escalade'),
    ('Cadillac', 'Lyriq'),
    ('Cadillac', 'Escalade IQ'),
    ('Cadillac', 'DeVille'),
    ('Cadillac', 'Eldorado'),
    ('Cadillac', 'Seville'),
    ('Cadillac', 'BLS'),
    ('Cadillac', 'ELR'),
    ('Infiniti', 'Q30'),
    ('Infiniti', 'Q50'),
    ('Infiniti', 'Q60'),
    ('Infiniti', 'Q70'),
    ('Infiniti', 'QX30'),
    ('Infiniti', 'QX50'),
    ('Infiniti', 'QX55'),
    ('Infiniti', 'QX60'),
    ('Infiniti', 'QX70'),
    ('Infiniti', 'QX80'),
    ('Infiniti', 'G25'),
    ('Infiniti', 'G35'),
    ('Infiniti', 'G37'),
    ('Infiniti', 'M25'),
    ('Infiniti', 'M35'),
    ('Infiniti', 'M37'),
    ('Infiniti', 'FX35'),
    ('Infiniti', 'FX37'),
    ('Infiniti', 'FX50'),
    ('Infiniti', 'EX25'),
    ('Infiniti', 'EX35'),
    ('Infiniti', 'JX35'),
    ('Infiniti', 'Q45'),
    ('Acura', 'ILX'),
    ('Acura', 'TLX'),
    ('Acura', 'RLX'),
    ('Acura', 'TL'),
    ('Acura', 'TSX'),
    ('Acura', 'RL'),
    ('Acura', 'RSX'),
    ('Acura', 'Integra'),
    ('Acura', 'MDX'),
    ('Acura', 'RDX'),
    ('Acura', 'ZDX'),
    ('Acura', 'NSX'),
    ('Acura', 'CL'),
    ('Acura', 'EL'),
    ('Acura', 'CSX'),
    ('DS Automobiles', 'DS 3'),
    ('DS Automobiles', 'DS 4'),
    ('DS Automobiles', 'DS 5'),
    ('DS Automobiles', 'DS 7'),
    ('DS Automobiles', 'DS 9'),
    ('DS Automobiles', 'DS 3 Crossback'),
    ('DS Automobiles', 'DS 4 Crossback'),
    ('DS Automobiles', 'DS 7 Crossback'),
    ('Genesis', 'G70'),
    ('Genesis', 'G80'),
    ('Genesis', 'G90'),
    ('Genesis', 'GV60'),
    ('Genesis', 'GV70'),
    ('Genesis', 'GV80'),
    ('Genesis', 'Coupe'),
    ('Polestar', '1'),
    ('Polestar', '2'),
    ('Polestar', '3'),
    ('Polestar', '4'),
    ('Polestar', '5'),
    ('SsangYong', 'Korando'),
    ('SsangYong', 'Rexton'),
    ('SsangYong', 'Tivoli'),
    ('SsangYong', 'Actyon'),
    ('SsangYong', 'Kyron'),
    ('SsangYong', 'Rodius'),
    ('SsangYong', 'Musso'),
    ('SsangYong', 'Chairman'),
    ('SsangYong', 'Korando Sports'),
    ('SsangYong', 'XLV'),
    ('SsangYong', 'Tivoli XLV'),
    ('SsangYong', 'Stavic'),
    ('SsangYong', 'Family'),
    ('SsangYong', 'Musso Grand'),
    ('KGM', 'Torres'),
    ('KGM', 'Actyon'),
    ('KGM', 'Rexton'),
    ('KGM', 'Tivoli'),
    ('KGM', 'Korando'),
    ('KGM', 'Musso'),
    ('Isuzu', 'D-Max'),
    ('Isuzu', 'MU-X'),
    ('Isuzu', 'Trooper'),
    ('Isuzu', 'Rodeo'),
    ('Isuzu', 'Amigo'),
    ('Isuzu', 'Ascender'),
    ('Isuzu', 'Axiom'),
    ('Isuzu', 'VehiCROSS'),
    ('Isuzu', 'Pickup'),
    ('Isuzu', 'KB'),
    ('Isuzu', 'TF'),
    ('Daihatsu', 'Terios'),
    ('Daihatsu', 'Sirion'),
    ('Daihatsu', 'Cuore'),
    ('Daihatsu', 'Charade'),
    ('Daihatsu', 'Materia'),
    ('Daihatsu', 'Copen'),
    ('Daihatsu', 'Rocky'),
    ('Daihatsu', 'YRV'),
    ('Daihatsu', 'Move'),
    ('Daihatsu', 'Mira'),
    ('Daihatsu', 'Hijet'),
    ('Daihatsu', 'Applause'),
    ('Daihatsu', 'Feroza'),
    ('Daihatsu', 'Gran Move'),
    ('Daihatsu', 'Sparcar'),
    ('Daewoo', 'Lanos'),
    ('Daewoo', 'Nexia'),
    ('Daewoo', 'Matiz'),
    ('Daewoo', 'Leganza'),
    ('Daewoo', 'Nubira'),
    ('Daewoo', 'Espero'),
    ('Daewoo', 'Kalos'),
    ('Daewoo', 'Tacuma'),
    ('Daewoo', 'Rezzo'),
    ('Daewoo', 'Evanda'),
    ('Daewoo', 'Gentra'),
    ('Daewoo', 'Sens'),
    ('Daewoo', 'Prince'),
    ('Daewoo', 'Super Salon'),
    ('Daewoo', 'Tico'),
    ('Datsun', 'on-Do'),
    ('Datsun', 'mi-Do'),
    ('Datsun', 'GO'),
    ('Datsun', 'GO+'),
    ('Datsun', '240Z'),
    ('Datsun', '260Z'),
    ('Datsun', '280Z'),
    ('Datsun', '280ZX'),
    ('Datsun', '510'),
    ('Datsun', '120Y'),
    ('Datsun', 'Cherry'),
    ('Datsun', 'Sunny'),
    ('Datsun', 'Bluebird'),
    ('Abarth', '500'),
    ('Abarth', '595'),
    ('Abarth', '695'),
    ('Abarth', '124 Spider'),
    ('Abarth', 'Punto'),
    ('Abarth', 'Grande Punto'),
    ('Abarth', '500e'),
    ('Lancia', 'Ypsilon'),
    ('Lancia', 'Delta'),
    ('Lancia', 'Thema'),
    ('Lancia', 'Thesis'),
    ('Lancia', 'Lybra'),
    ('Lancia', 'Kappa'),
    ('Lancia', 'Dedra'),
    ('Lancia', 'Prisma'),
    ('Lancia', 'Beta'),
    ('Lancia', 'Gamma'),
    ('Lancia', 'Fulvia'),
    ('Lancia', 'Flavia'),
    ('Lancia', 'Musa'),
    ('Lancia', 'Phedra'),
    ('Lancia', 'Voyager'),
    ('Lancia', 'Zeta'),
    ('BYD', 'Atto 3'),
    ('BYD', 'Dolphin'),
    ('BYD', 'Seal'),
    ('BYD', 'Seal U'),
    ('BYD', 'Han'),
    ('BYD', 'Tang'),
    ('BYD', 'Song'),
    ('BYD', 'Qin'),
    ('BYD', 'Yuan'),
    ('BYD', 'Destroyer 05'),
    ('BYD', 'Sealion 6'),
    ('BYD', 'Sealion 7'),
    ('BYD', 'Yangwang U8'),
    ('BYD', 'e6'),
    ('BYD', 'F3'),
    ('BYD', 'F0'),
    ('BYD', 'S6'),
    ('BYD', 'S7'),
    ('BYD', 'G3'),
    ('BYD', 'L3'),
    ('BYD', 'Atto 2'),
    ('Chery', 'Tiggo 2'),
    ('Chery', 'Tiggo 3'),
    ('Chery', 'Tiggo 4'),
    ('Chery', 'Tiggo 7'),
    ('Chery', 'Tiggo 8'),
    ('Chery', 'Tiggo 9'),
    ('Chery', 'Arrizo 5'),
    ('Chery', 'Arrizo 6'),
    ('Chery', 'Arrizo 7'),
    ('Chery', 'Arrizo 8'),
    ('Chery', 'QQ'),
    ('Chery', 'Amulet'),
    ('Chery', 'Fora'),
    ('Chery', 'Bonus'),
    ('Chery', 'Very'),
    ('Chery', 'IndiS'),
    ('Chery', 'CrossEastar'),
    ('Chery', 'Eastar'),
    ('Chery', 'A1'),
    ('Chery', 'A3'),
    ('Chery', 'A5'),
    ('Chery', 'J11'),
    ('Chery', 'Tiggo 5'),
    ('Chery', 'Tiggo 8 Pro'),
    ('Geely', 'Coolray'),
    ('Geely', 'Atlas'),
    ('Geely', 'Emgrand'),
    ('Geely', 'Emgrand 7'),
    ('Geely', 'Emgrand X7'),
    ('Geely', 'Preface'),
    ('Geely', 'Tugella'),
    ('Geely', 'Monjaro'),
    ('Geely', 'Okavango'),
    ('Geely', 'Geometry C'),
    ('Geely', 'Geometry A'),
    ('Geely', 'CK'),
    ('Geely', 'MK'),
    ('Geely', 'FC'),
    ('Geely', 'SC7'),
    ('Geely', 'GC6'),
    ('Geely', 'GC9'),
    ('Geely', 'Boyue'),
    ('Geely', 'Xingyue'),
    ('Geely', 'Galaxy L7'),
    ('Geely', 'Galaxy E5'),
    ('Haval', 'H2'),
    ('Haval', 'H6'),
    ('Haval', 'H9'),
    ('Haval', 'Jolion'),
    ('Haval', 'Dargo'),
    ('Haval', 'F7'),
    ('Haval', 'F7x'),
    ('Haval', 'H5'),
    ('Haval', 'H8'),
    ('Haval', 'M6'),
    ('Haval', 'H3'),
    ('Haval', 'H7'),
    ('Haval', 'H4'),
    ('Haval', 'Jolion Pro'),
    ('Great Wall', 'Hover'),
    ('Great Wall', 'Hover H3'),
    ('Great Wall', 'Hover H5'),
    ('Great Wall', 'Hover H6'),
    ('Great Wall', 'Safe'),
    ('Great Wall', 'Deer'),
    ('Great Wall', 'Wingle'),
    ('Great Wall', 'Wingle 5'),
    ('Great Wall', 'Wingle 7'),
    ('Great Wall', 'Poer'),
    ('Great Wall', 'Cannon'),
    ('Great Wall', 'Steed'),
    ('Great Wall', 'Voleex C30'),
    ('Great Wall', 'Voleex C50'),
    ('Great Wall', 'Florid'),
    ('Great Wall', 'Cowry'),
    ('MG', 'MG3'),
    ('MG', 'MG4'),
    ('MG', 'MG5'),
    ('MG', 'MG6'),
    ('MG', 'MG7'),
    ('MG', 'ZS'),
    ('MG', 'HS'),
    ('MG', 'GS'),
    ('MG', 'GT'),
    ('MG', 'Marvel R'),
    ('MG', 'Cyberster'),
    ('MG', 'TF'),
    ('MG', 'ZR'),
    ('MG', 'MGB'),
    ('MG', 'MGA'),
    ('MG', 'MGF'),
    ('MG', 'RV8'),
    ('MG', 'Hector'),
    ('MG', 'Astor'),
    ('MG', 'Gloster'),
    ('Omoda', 'C5'),
    ('Omoda', 'E5'),
    ('Omoda', 'C7'),
    ('Omoda', 'S5'),
    ('Jaecoo', 'J5'),
    ('Jaecoo', 'J7'),
    ('Jaecoo', 'J8'),
    ('Exeed', 'TXL'),
    ('Exeed', 'VX'),
    ('Exeed', 'RX'),
    ('Exeed', 'LX'),
    ('Exeed', 'ATX'),
    ('Changan', 'CS35'),
    ('Changan', 'CS55'),
    ('Changan', 'CS75'),
    ('Changan', 'CS85'),
    ('Changan', 'CS95'),
    ('Changan', 'Alsvin'),
    ('Changan', 'Eado'),
    ('Changan', 'Raeton'),
    ('Changan', 'UNI-K'),
    ('Changan', 'UNI-T'),
    ('Changan', 'UNI-V'),
    ('Changan', 'Hunter'),
    ('Changan', 'Benben'),
    ('Changan', 'CS15'),
    ('Changan', 'Deepal S7'),
    ('Changan', 'Lamore'),
    ('Dongfeng', 'AX7'),
    ('Dongfeng', 'AX4'),
    ('Dongfeng', '580'),
    ('Dongfeng', '370'),
    ('Dongfeng', 'H30'),
    ('Dongfeng', 'S30'),
    ('Dongfeng', 'A30'),
    ('Dongfeng', 'Rich'),
    ('Dongfeng', 'Paladin'),
    ('Dongfeng', 'Fengon 500'),
    ('Dongfeng', 'Fengon 580'),
    ('Dongfeng', 'Shine'),
    ('Dongfeng', 'Aeolus Haohan'),
    ('BAIC', 'X35'),
    ('BAIC', 'X55'),
    ('BAIC', 'X65'),
    ('BAIC', 'BJ40'),
    ('BAIC', 'BJ80'),
    ('BAIC', 'Senova D50'),
    ('BAIC', 'Senova X25'),
    ('BAIC', 'Senova X55'),
    ('BAIC', 'EU5'),
    ('BAIC', 'EU7'),
    ('BAIC', 'Beijing X7'),
    ('GAC', 'GS3'),
    ('GAC', 'GS4'),
    ('GAC', 'GS5'),
    ('GAC', 'GS8'),
    ('GAC', 'GA4'),
    ('GAC', 'GA6'),
    ('GAC', 'GA8'),
    ('GAC', 'GN8'),
    ('GAC', 'Emkoo'),
    ('GAC', 'Emzoom'),
    ('FAW', 'Besturn B30'),
    ('FAW', 'Besturn B50'),
    ('FAW', 'Besturn B70'),
    ('FAW', 'Besturn X40'),
    ('FAW', 'Besturn X80'),
    ('FAW', 'Vita'),
    ('FAW', 'V2'),
    ('FAW', 'V5'),
    ('FAW', 'Oley'),
    ('JAC', 'S2'),
    ('JAC', 'S3'),
    ('JAC', 'S4'),
    ('JAC', 'S5'),
    ('JAC', 'S7'),
    ('JAC', 'T6'),
    ('JAC', 'T8'),
    ('JAC', 'J7'),
    ('JAC', 'iEV7S'),
    ('JAC', 'JS3'),
    ('JAC', 'JS4'),
    ('JAC', 'JS6'),
    ('JAC', 'Refine'),
    ('JAC', 'Heyue'),
    ('Jetour', 'X70'),
    ('Jetour', 'X70 Plus'),
    ('Jetour', 'X90'),
    ('Jetour', 'X90 Plus'),
    ('Jetour', 'Dashing'),
    ('Jetour', 'T2'),
    ('Jetour', 'X95'),
    ('Hongqi', 'H5'),
    ('Hongqi', 'H7'),
    ('Hongqi', 'H9'),
    ('Hongqi', 'HS5'),
    ('Hongqi', 'HS7'),
    ('Hongqi', 'E-HS9'),
    ('Hongqi', 'E-QM5'),
    ('Hongqi', 'L5'),
    ('Tank', '300'),
    ('Tank', '400'),
    ('Tank', '500'),
    ('Tank', '700'),
    ('Wey', 'Coffee 01'),
    ('Wey', 'Coffee 02'),
    ('Wey', 'Mocha'),
    ('Wey', 'Latte'),
    ('Wey', 'Macchiato'),
    ('Wey', 'VV5'),
    ('Wey', 'VV6'),
    ('Wey', 'VV7'),
    ('Lynk & Co', '01'),
    ('Lynk & Co', '02'),
    ('Lynk & Co', '03'),
    ('Lynk & Co', '05'),
    ('Lynk & Co', '06'),
    ('Lynk & Co', '07'),
    ('Lynk & Co', '08'),
    ('Lynk & Co', '09'),
    ('Zeekr', '001'),
    ('Zeekr', '007'),
    ('Zeekr', '009'),
    ('Zeekr', 'X'),
    ('Zeekr', '7X'),
    ('Zeekr', 'RT'),
    ('NIO', 'ET5'),
    ('NIO', 'ET7'),
    ('NIO', 'ES6'),
    ('NIO', 'ES7'),
    ('NIO', 'ES8'),
    ('NIO', 'EC6'),
    ('NIO', 'EC7'),
    ('NIO', 'EL6'),
    ('NIO', 'EL7'),
    ('NIO', 'EL8'),
    ('NIO', 'ET9'),
    ('XPeng', 'G3'),
    ('XPeng', 'G6'),
    ('XPeng', 'G9'),
    ('XPeng', 'P5'),
    ('XPeng', 'P7'),
    ('XPeng', 'X9'),
    ('Leapmotor', 'T03'),
    ('Leapmotor', 'C10'),
    ('Leapmotor', 'C11'),
    ('Leapmotor', 'C16'),
    ('Leapmotor', 'C01'),
    ('Leapmotor', 'B10'),
    ('Li Auto', 'L6'),
    ('Li Auto', 'L7'),
    ('Li Auto', 'L8'),
    ('Li Auto', 'L9'),
    ('Li Auto', 'MEGA'),
    ('Li Auto', 'ONE'),
    ('ORA', 'Funky Cat'),
    ('ORA', 'Good Cat'),
    ('ORA', 'Lightning Cat'),
    ('ORA', 'Ballet Cat'),
    ('ORA', '03'),
    ('ORA', '07'),
    ('Maxus', 'G10'),
    ('Maxus', 'G20'),
    ('Maxus', 'G50'),
    ('Maxus', 'D60'),
    ('Maxus', 'D90'),
    ('Maxus', 'T60'),
    ('Maxus', 'T70'),
    ('Maxus', 'T90'),
    ('Maxus', 'Euniq 5'),
    ('Maxus', 'Euniq 6'),
    ('Maxus', 'MIFA 9'),
    ('Maxus', 'Deliver 9'),
    ('Seres', '3'),
    ('Seres', '5'),
    ('Seres', '7'),
    ('Seres', 'SF5'),
    ('Voyah', 'Free'),
    ('Voyah', 'Dream'),
    ('Voyah', 'Passionate'),
    ('Voyah', 'Courage'),
    ('Aion', 'S'),
    ('Aion', 'Y'),
    ('Aion', 'V'),
    ('Aion', 'LX'),
    ('Aion', 'Hyper GT'),
    ('Aion', 'Hyper SSR'),
    ('Bestune', 'T55'),
    ('Bestune', 'T77'),
    ('Bestune', 'T99'),
    ('Bestune', 'B70'),
    ('Bestune', 'NAT'),
    ('Bestune', 'T33'),
    ('DFSK', '500'),
    ('DFSK', '580'),
    ('DFSK', 'Fengon 500'),
    ('DFSK', 'Fengon 580'),
    ('DFSK', 'Glory 580'),
    ('DFSK', 'C31'),
    ('DFSK', 'C32'),
    ('DFSK', 'C35'),
    ('DFSK', 'K01'),
    ('DFSK', 'K07'),
    ('Foton', 'Sauvana'),
    ('Foton', 'Tunland'),
    ('Foton', 'View'),
    ('Foton', 'Toano'),
    ('Foton', 'Midi'),
    ('VinFast', 'VF 3'),
    ('VinFast', 'VF 5'),
    ('VinFast', 'VF 6'),
    ('VinFast', 'VF 7'),
    ('VinFast', 'VF 8'),
    ('VinFast', 'VF 9'),
    ('VinFast', 'VF e34'),
    ('Lada', 'Granta'),
    ('Lada', 'Vesta'),
    ('Lada', 'Niva'),
    ('Lada', 'Niva Travel'),
    ('Lada', 'Largus'),
    ('Lada', 'Kalina'),
    ('Lada', 'Priora'),
    ('Lada', 'XRAY'),
    ('Lada', '2107'),
    ('Lada', '2106'),
    ('Lada', '2105'),
    ('Lada', '2104'),
    ('Lada', '2101'),
    ('Lada', '2108'),
    ('Lada', '2109'),
    ('Lada', '21099'),
    ('Lada', '2110'),
    ('Lada', '2111'),
    ('Lada', '2112'),
    ('Lada', '2113'),
    ('Lada', '2114'),
    ('Lada', '2115'),
    ('Lada', 'Samara'),
    ('Lada', '4x4'),
    ('Lada', 'Iskra'),
    ('Lada', 'Niva Legend'),
    ('Lada', '110'),
    ('Lada', '111'),
    ('Lada', '112'),
    ('Lada', 'Oka'),
    ('UAZ', 'Patriot'),
    ('UAZ', 'Hunter'),
    ('UAZ', '469'),
    ('UAZ', '452'),
    ('UAZ', 'Pickup'),
    ('UAZ', 'Profi'),
    ('UAZ', 'Bukhanka'),
    ('UAZ', '3151'),
    ('UAZ', '3163'),
    ('Moskvich', '412'),
    ('Moskvich', '2140'),
    ('Moskvich', '2141'),
    ('Moskvich', '3'),
    ('Moskvich', '6'),
    ('Moskvich', 'Aleko'),
    ('Moskvich', '408'),
    ('Moskvich', '2138'),
    ('Moskvich', '400'),
    ('Moskvich', '401'),
    ('Moskvich', '423');
